[package]
name = "anon-flatten"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
colored = "3.0.0"
fs_extra = "1.3.0"
indicatif = "0.17.11"
walkdir = "2.5.0"

[dev-dependencies]
tempfile = "3.20.0"
